feat: get configurations from haugene's repository

diff --git a/etc/cont-init.d/02-setup-openvpn b/etc/cont-init.d/02-setup-openvpn
--- a/etc/cont-init.d/02-setup-openvpn
+++ b/etc/cont-init.d/02-setup-openvpn
@@ -13,3 +13,29 @@ echo "${OPENVPN_PASSWORD}" >>${CREDENTIALS_FILE}
 chmod 600 ${CREDENTIALS_FILE}
 
 echo "nameserver ${DNS}" >/etc/resolv.conf
+
+if [[ "${OPENVPN_PROVIDER}" == "**None**" ]] || [[ -z "${OPENVPN_PROVIDER-}" ]]; then
+    echo "OpenVPN provider not set. Using configuration at ${OPENVPN_CONFIG_FILE}"
+    exit 0
+fi
+
+echo "Trying to use OpenVPN provider: ${OPENVPN_PROVIDER}"
+
+lowercase_openvpn_provider=$(echo "${OPENVPN_PROVIDER}" | awk '{print tolower($0)}')
+VPN_PROVIDER_CONFIGS="https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/${lowercase_openvpn_provider}"
+
+if [[ -n "${OPENVPN_CONFIG}" ]]; then
+    OPENVPN_CONFIG_URL="${VPN_PROVIDER_CONFIGS}/${OPENVPN_CONFIG}.ovpn"
+else
+    echo "No VPN configuration provided. Using default."
+    OPENVPN_CONFIG_URL="${VPN_PROVIDER_CONFIGS}/default.ovpn"
+fi
+
+wget ${OPENVPN_CONFIG_URL} -O ${OPENVPN_CONFIG_FILE}
+
+if [ $? -ne 0 ]; then
+    echo "ERROR: Could not find OpenVPN configuration for provider ${OPENVPN_PROVIDER} at ${OPENVPN_CONFIG_URL}"
+    exit 1
+else
+    echo "Found OpenVPN configuration: ${OPENVPN_CONFIG_FILE} for provider ${OPENVPN_PROVIDER} at ${OPENVPN_CONFIG_URL} using it"
+fi
diff --git a/etc/cont-init.d/03-setup-iptables b/etc/cont-init.d/03-setup-iptables
--- a/etc/cont-init.d/03-setup-iptables
+++ b/etc/cont-init.d/03-setup-iptables
@@ -2,9 +2,18 @@
 
 DOCKER_CIDR=$(ip -o -f inet addr show | awk '/scope global/ {print $4}')
 
-VPN_PROTO=$(awk '/proto / { print $2 }' "${OPENVPN_CONFIG}")
-VPN_HOST=$(awk '/remote / { print $2 }' "${OPENVPN_CONFIG}")
-VPN_PORT=$(awk '/remote / { print $3 }' "${OPENVPN_CONFIG}")
+VPN_PROTO=$(awk '/proto / { print $2 }' "${OPENVPN_CONFIG_FILE}")
+VPN_HOST=$(awk '/remote / { print $2 }' "${OPENVPN_CONFIG_FILE}")
+VPN_PORT=$(awk '/remote / { print $3 }' "${OPENVPN_CONFIG_FILE}")
+
+if [[ -z "${VPN_PROTO}" || -z "${VPN_HOST}" || -z "${VPN_PORT}" ]]; then
+    echo "One of the following variables could not be detected in the VPN configuration:
+    VPN_PROTO:  $VPN_PROTO
+    VPN_HOST:   $VPN_HOST
+    VPN_PORT:   $VPN_PORT
+    "
+    exit 1
+fi
 
 echo "nameserver ${DNS}" >/etc/resolv.conf
 
